bind -r C-j resizep -D
bind -r C-k resizep -U
bind -r C-h resizep -L
bind -r C-l resizep -R
bind j selectp -D
bind k selectp -U
bind h selectp -L
bind l selectp -R
 
#rebinding default l keybinding to Right:
bind Right last 

set -g mode-keys vi
set -g status-keys vi

set -g status-style fg=yellow 
set -ag status-style bg=blue
set -g status-position top
set -g clock-mode-colour red
set -g pane-border-style bg=magenta
set -g pane-active-border-style bg=red
set -g clock-mode-style 12-with-seconds
set -g copy-mode-selection-style bg=cyan
set -g window-style fg=blue
set -ag window-style bg=yellow 
